### ISSUE TITLE
post了data后 返回验证码错误 已解决

### ISSUE THREAD

**Issue by 7est** [vhyz/ZF_Spider#1]
如题

保证输入时的编码没问题。
print了data本身，是输入的参数没问题。
网页中的元素name和data提交的字典键值吻合。
print了request.text后发现返回中有提示验证码错误。

已解决

**Comment by test2g** [comment]
好的👌

**Comment by vhyz** [comment]
刚看了下，有些细节没有弄好，现在应该可以登录了。
